// Emit src/generated/BoardConfig.h from FirmwareConfig.
// Chip type + color order become FastLED template args (compile-time only).

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import {
  COLOR_ORDERS,
  LED_TYPES,
  cStringLiteral,
  type FirmwareConfig,
} from "./config.ts";

export function generateBoardConfigHeader(
  firmwareRoot: string,
  cfg: FirmwareConfig,
): string {
  const outDir = path.join(firmwareRoot, "src", "generated");
  mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, "BoardConfig.h");

  const meta = LED_TYPES[cfg.leds.type];
  const order = COLOR_ORDERS[cfg.leds.order];
  const hasClock = meta.needsClock && cfg.leds.clockPin != null;

  const body = `// AUTO-GENERATED by resolight/firmware/scripts — do not edit.
// Source: config.yaml  →  pnpm --dir resolight/firmware build|flash
#pragma once

#define RESOLIGHT_WIFI_SSID "${cStringLiteral(cfg.wifi.ssid)}"
#define RESOLIGHT_WIFI_PASS "${cStringLiteral(cfg.wifi.password)}"

#define RESOLIGHT_LED_PIN ${cfg.leds.pin}
#define RESOLIGHT_LED_COUNT ${cfg.leds.count}
#define RESOLIGHT_LED_BRIGHTNESS ${cfg.leds.brightness}

// FastLED template args (chip + wire color order).
#define RESOLIGHT_LED_CHIP ${meta.chip}
#define RESOLIGHT_LED_ORDER ${order}
${hasClock ? `#define RESOLIGHT_LED_CLOCK_PIN ${cfg.leds.clockPin}\n#define RESOLIGHT_LED_HAS_CLOCK 1` : `#define RESOLIGHT_LED_HAS_CLOCK 0`}

// Human-readable (for Serial logs / debugging).
#define RESOLIGHT_LED_TYPE_NAME "${cfg.leds.type}"
#define RESOLIGHT_BOARD_ENV "${cfg.board}"
`;

  writeFileSync(outPath, body, "utf8");
  return outPath;
}
