/*
 * ResoStage — Deterministic Real-Time Live Performance Workstation
 * Copyright © 2026 Andrii Vynohradov. All rights reserved.
 * Licensed under the GNU General Public License v3.0 or later; see LICENSE.
 */

#include "MixLatency.h"

#include <algorithm>
#include <limits>

namespace resostage {
namespace {

uint32_t saturatingAdd(uint32_t left, uint32_t right) {
    const uint64_t sum = static_cast<uint64_t>(left) + right;
    return static_cast<uint32_t>(
        std::min<uint64_t>(sum, std::numeric_limits<uint32_t>::max()));
}

} // namespace

MixLatencyPlan buildMixLatencyPlan(
    const MixGraph& graph,
    const std::vector<uint32_t>& stripProcessorLatencySamples,
    const std::vector<std::vector<uint32_t>>& stripPluginSlotLatencySamples) {
    MixLatencyPlan plan;
    plan.stripInputDelaySamples.assign(graph.strips.size(), 0);
    plan.edgeDelaySamples.assign(graph.edges.size(), 0);
    plan.sidechainEdgeDelaySamples.assign(graph.sidechainEdges.size(), 0);
    plan.sidechainAlignmentUnavailable.assign(graph.sidechainEdges.size(), false);
    plan.stripOutputLatencySamples.assign(graph.strips.size(), 0);
    std::vector<uint32_t> stripInputLatencySamples(graph.strips.size(), 0);

    // Both edge lists are destination-sorted and the graph is topologically
    // ordered. Thus every upstream path is final before a destination's
    // normal or auxiliary inputs are considered.
    size_t edgeCursor = 0;
    size_t sidechainCursor = 0;
    for (uint32_t strip = 0; strip < graph.strips.size(); ++strip) {
        // A strip's own stream/live input is an implicit zero-latency source,
        // not a MixEdge. It must be delayed too when a later path (including
        // a sidechain) requires the whole strip input to arrive later.
        uint32_t inputLatency = 0;
        while (edgeCursor < graph.edges.size()
               && graph.edges[edgeCursor].to == strip) {
            const auto& edge = graph.edges[edgeCursor++];
            if (edge.from < plan.stripOutputLatencySamples.size()) {
                inputLatency = std::max(
                    inputLatency,
                    plan.stripOutputLatencySamples[edge.from]);
            }
        }

        while (sidechainCursor < graph.sidechainEdges.size()
               && graph.sidechainEdges[sidechainCursor].to < strip)
            ++sidechainCursor;
        while (sidechainCursor < graph.sidechainEdges.size()
               && graph.sidechainEdges[sidechainCursor].to == strip) {
            const auto& edge = graph.sidechainEdges[sidechainCursor++];
            if (edge.from >= plan.stripOutputLatencySamples.size())
                continue;

            uint32_t latencyBeforeSlot = 0;
            if (strip < stripPluginSlotLatencySamples.size()) {
                const auto& slotLatencies = stripPluginSlotLatencySamples[strip];
                const size_t prefixCount = std::min<size_t>(
                    edge.pluginSlotIndex, slotLatencies.size());
                for (size_t slot = 0; slot < prefixCount; ++slot)
                    latencyBeforeSlot = saturatingAdd(
                        latencyBeforeSlot, slotLatencies[slot]);
            }

            const uint32_t sourceLatency =
                plan.stripOutputLatencySamples[edge.from];
            const uint32_t requiredInputLatency =
                sourceLatency > latencyBeforeSlot
                    ? sourceLatency - latencyBeforeSlot
                    : 0;
            // A pre-chain pad can align streamed audio, but it cannot delay
            // audio generated by an instrument insert. In that case only the
            // auxiliary feed can be delayed; a late feed is reported below.
            if (!graph.strips[strip].isInstrumentTrack)
                inputLatency = std::max(inputLatency, requiredInputLatency);
        }

        stripInputLatencySamples[strip] = inputLatency;
        const auto kind = graph.strips[strip].kind;
        if ((kind == StripKind::Track || kind == StripKind::Click)
            && !graph.strips[strip].isInstrumentTrack)
            plan.stripInputDelaySamples[strip] = inputLatency;
        const uint32_t processorLatency =
            strip < stripProcessorLatencySamples.size()
                ? stripProcessorLatencySamples[strip]
                : 0;
        plan.stripOutputLatencySamples[strip] =
            saturatingAdd(inputLatency, processorLatency);
        plan.maximumOutputLatencySamples = std::max(
            plan.maximumOutputLatencySamples,
            plan.stripOutputLatencySamples[strip]);
    }

    for (size_t edgeIndex = 0; edgeIndex < graph.edges.size(); ++edgeIndex) {
        const auto& edge = graph.edges[edgeIndex];
        if (edge.from >= plan.stripOutputLatencySamples.size()
            || edge.to >= stripInputLatencySamples.size()) {
            continue;
        }
        const uint32_t sourceLatency =
            plan.stripOutputLatencySamples[edge.from];
        const uint32_t destinationLatency =
            stripInputLatencySamples[edge.to];
        plan.edgeDelaySamples[edgeIndex] =
            destinationLatency > sourceLatency
                ? destinationLatency - sourceLatency
                : 0;
    }

    for (size_t edgeIndex = 0;
         edgeIndex < graph.sidechainEdges.size(); ++edgeIndex) {
        const auto& edge = graph.sidechainEdges[edgeIndex];
        if (edge.from >= plan.stripOutputLatencySamples.size()
            || edge.to >= stripInputLatencySamples.size())
            continue;

        uint32_t latencyBeforeSlot = 0;
        if (edge.to < stripPluginSlotLatencySamples.size()) {
            const auto& slotLatencies =
                stripPluginSlotLatencySamples[edge.to];
            const size_t prefixCount = std::min<size_t>(
                edge.pluginSlotIndex, slotLatencies.size());
            for (size_t slot = 0; slot < prefixCount; ++slot)
                latencyBeforeSlot = saturatingAdd(
                    latencyBeforeSlot, slotLatencies[slot]);
        }

        const bool instrumentTarget = graph.strips[edge.to].isInstrumentTrack;
        const uint32_t destinationSlotLatency = saturatingAdd(
            instrumentTarget ? 0 : stripInputLatencySamples[edge.to],
            latencyBeforeSlot);
        const uint32_t sourceLatency =
            plan.stripOutputLatencySamples[edge.from];
        if (instrumentTarget && sourceLatency > destinationSlotLatency)
            plan.sidechainAlignmentUnavailable[edgeIndex] = true;
        plan.sidechainEdgeDelaySamples[edgeIndex] =
            destinationSlotLatency > sourceLatency
                ? destinationSlotLatency - sourceLatency
                : 0;
    }
    return plan;
}

} // namespace resostage
